# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 10:07
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wishlist.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boutique1', '0021_auto_20170828_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='wish_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('image_category', models.ImageField(blank=True, null=True, upload_to=wishlist.models.user_directory_path_five)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2017, 8, 28, 10, 7, 38, 197101))),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='wish_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='boutique1.Produit')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wish_category', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='wishlist.wish_category')),
            ],
        ),
    ]
