# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 04:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique1', '0022_auto_20170829_0414'),
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish_category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 29, 4, 14, 1, 618662)),
        ),
        migrations.RemoveField(
            model_name='wish_list',
            name='produit',
        ),
        migrations.AddField(
            model_name='wish_list',
            name='produit',
            field=models.ManyToManyField(default=0, to='boutique1.Produit'),
        ),
    ]
