# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 15:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boutique1', '0023_auto_20170829_1550'),
        ('wishlist', '0002_auto_20170829_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish_category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 29, 15, 50, 51, 854998)),
        ),
        migrations.RemoveField(
            model_name='wish_list',
            name='produit',
        ),
        migrations.AddField(
            model_name='wish_list',
            name='produit',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='boutique1.Produit'),
        ),
    ]
