# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 16:21
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boutique1', '0024_auto_20170829_1621'),
        ('wishlist', '0003_auto_20170829_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish_category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 29, 16, 21, 13, 573993)),
        ),
        migrations.AlterUniqueTogether(
            name='wish_list',
            unique_together=set([('user', 'wish_category', 'produit')]),
        ),
    ]
