# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boutique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_boutique', models.CharField(max_length=250)),
                ('logo_boutique', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(max_length=250)),
                ('image_produit', models.FileField(upload_to='')),
                ('prix_produit', models.FloatField()),
                ('description', models.CharField(max_length=1000)),
                ('Boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boutique1.Boutique')),
            ],
        ),
    ]
