# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 09:57
from __future__ import unicode_literals

import boutique1.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boutique1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2500, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=boutique1.models.user_directory_path_three)),
                ('fb_link', models.CharField(max_length=100)),
                ('instagram_link', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('commercant_type', models.CharField(blank=True, choices=[('PA', 'Particular'), ('SO', 'Society')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
