# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boutique1', '0002_category_trader'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='boutique1.Trader'),
        ),
        migrations.AddField(
            model_name='produit',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='boutique1.Category'),
        ),
        migrations.AddField(
            model_name='produit',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='boutique1.Trader'),
        ),
    ]
