# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 10:07
from __future__ import unicode_literals

import boutique1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique1', '0003_auto_20170808_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='product_type',
            field=models.CharField(blank=True, choices=[('HM', 'Hand Made'), ('VTG', 'Vintage')], max_length=20),
        ),
        migrations.AddField(
            model_name='produit',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='produit',
            name='secondary_picture1',
            field=models.ImageField(blank=True, null=True, upload_to=boutique1.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='produit',
            name='secondary_picture2',
            field=models.ImageField(blank=True, null=True, upload_to=boutique1.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='produit',
            name='secondary_picture3',
            field=models.ImageField(blank=True, null=True, upload_to=boutique1.models.user_directory_path),
        ),
    ]
