# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 10:59
from __future__ import unicode_literals

import boutique1.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique1', '0006_auto_20170814_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='image_collection',
            field=models.ImageField(blank=True, null=True, upload_to=boutique1.models.user_directory_path_four),
        ),
        migrations.AlterField(
            model_name='collection',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 14, 11, 59, 34, 783137)),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 14, 11, 59, 34, 785138)),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 14, 11, 59, 34, 785138)),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 14, 11, 59, 34, 785138)),
        ),
    ]
