# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 10:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique1', '0009_auto_20170817_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='collection',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 17, 11, 37, 3, 475993)),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 17, 11, 37, 3, 477994)),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 17, 11, 37, 3, 477994)),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 17, 11, 37, 3, 477994)),
        ),
    ]
