# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 15:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique1', '0010_auto_20170817_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 17, 16, 13, 3, 73766)),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 17, 16, 13, 3, 74766)),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 17, 16, 13, 3, 74766)),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='promotion_type',
            field=models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Flash', 'Flash')], max_length=20),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 17, 16, 13, 3, 74766)),
        ),
    ]
