# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 02:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique1', '0016_auto_20170822_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='en_promotion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='collection',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 2, 49, 55, 486827)),
        ),
    ]
