# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 13:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique1', '0017_auto_20170823_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='tz',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='collection',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 25, 13, 20, 25, 320317)),
        ),
    ]
