# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 15:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique1', '0022_auto_20170829_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 29, 15, 50, 51, 851752)),
        ),
    ]
