# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 02:21
from __future__ import unicode_literals

import album.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boutique1', '0025_auto_20170830_0221'),
    ]

    operations = [
        migrations.CreateModel(
            name='album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('image_album', models.ImageField(blank=True, null=True, upload_to=album.models.user_directory_path_one)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2017, 8, 30, 2, 21, 12, 505088))),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='boutique1.Trader')),
            ],
        ),
        migrations.CreateModel(
            name='picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('image_category', models.ImageField(blank=True, null=True, upload_to=album.models.user_directory_path_two)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2017, 8, 30, 2, 21, 12, 505987))),
                ('album', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='album.album')),
            ],
        ),
    ]
