# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 02:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_auto_20170830_0222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='image_category',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='album',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 30, 2, 51, 3, 26129)),
        ),
        migrations.AlterField(
            model_name='picture',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 30, 2, 51, 3, 26878)),
        ),
    ]
