# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 02:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_auto_20170830_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 30, 2, 54, 33, 398707)),
        ),
        migrations.AlterField(
            model_name='picture',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 30, 2, 54, 33, 399578)),
        ),
    ]
